-- Devarapus Supabase setup
-- Run this in Supabase SQL Editor.
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('home','electronics')),
  price numeric(12,2) not null,
  old_price numeric(12,2),
  image text,
  badge text default 'NEW',
  rating numeric(2,1) default 5,
  stock integer default 0,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  pincode text not null,
  payment_method text not null,
  total numeric(12,2) not null,
  status text default 'New',
  items jsonb not null,
  created_at timestamptz default now()
);

alter table products enable row level security;
alter table orders enable row level security;

-- Public customers can read active products.
create policy "public read active products" on products
for select using (active = true);

-- Demo/public order creation. For production, tighten this policy after
-- enabling Supabase Auth or a server-side checkout endpoint.
create policy "public create orders" on orders
for insert with check (true);

-- Admin reads/updates should be done through authenticated users.
-- Create an admin user in Supabase Authentication and then add policies
-- for authenticated admin access if you use the hosted backend.
